### ISSUE TITLE
step_freq not defined

### ISSUE THREAD

**Issue by muschellij2** [MStraczkiewicz/find_walking#1]
`step_freq` is required in https://github.com/MStraczkiewicz/find_walking/blob/main/find_walking.m#L2, but not defined in comments https://github.com/MStraczkiewicz/find_walking/blob/main/find_walking.m#L28

**Comment by MStraczkiewicz** [comment]
Thank you @muschellij2 . The issue has been addressed.

**Comment by MStraczkiewicz** [comment]
Closing.
